# Generated by Django 3.1.7 on 2021-03-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
